[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_OTC_WALLET = "UQB-Q4l7vp-RiXhSfziofwYpZ-Gv5Gs4xI9ZL3_tghEtjFpr"
  VITE_JETTON_ADDRESS = "EQB0beTxStmdhVri4s-cYlwYJaG_ZiR5lpLufCNC2VWUxZc-"
  VITE_POOL_ADDRESS = "EQCGEHrBuuoKVJ_0LqQy38F-c-pN-Jrz0M_ASdCtJxZL74nS"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/tonconnect-manifest.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
